use anyhow::{Context, Result};
use serde::Deserialize;
use tracing::{debug, trace, warn};

/// Detect if Hyprland is the current compositor.
/// Checks `HYPRLAND_INSTANCE_SIGNATURE` env var or availability of `hyprctl`.
pub fn detect_hyprland() -> bool {
    if std::env::var_os("HYPRLAND_INSTANCE_SIGNATURE").is_some() {
        trace!("HYPRLAND_INSTANCE_SIGNATURE detected");
        return true;
    }
    if which::which("hyprctl").is_ok() {
        trace!("hyprctl found in PATH");
        return true;
    }
    false
}

/// Information about a monitor.
#[derive(Debug, Clone, Deserialize)]
pub struct MonitorInfo {
    pub id: u64,
    pub name: String,
    pub description: String,
    pub width: u64,
    pub height: u64,
    pub refresh_rate: f64,
    pub x: i64,
    pub y: i64,
    pub active_workspace: WorkspaceRef,
    pub reserved: Vec<u64>,
    pub scale: f64,
    pub transform: u64,
    pub dpms: bool,
    pub vrr: Option<bool>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct WorkspaceRef {
    pub id: u64,
    pub name: String,
}

/// Information about a workspace.
#[derive(Debug, Clone, Deserialize)]
pub struct WorkspaceInfo {
    pub id: u64,
    pub name: String,
    pub monitor: String,
    pub windows: u64,
    pub hasfullscreen: bool,
    pub lastwindow: String,
    pub lastwindowtitle: String,
}

/// Query `hyprctl monitors -j` and return parsed info.
pub async fn get_active_monitor() -> Result<MonitorInfo> {
    if !detect_hyprland() {
        anyhow::bail!("Hyprland not detected");
    }
    let output = tokio::process::Command::new("hyprctl")
        .args(["monitors", "-j"])
        .output()
        .await
        .context("Failed to execute hyprctl monitors -j")?;
    if !output.status.success() {
        anyhow::bail!(
            "hyprctl exited with status {:?}",
            output.status.code()
        );
    }
    let monitors: Vec<MonitorInfo> =
        serde_json::from_slice(&output.stdout).context("Failed to parse hyprctl JSON")?;
    monitors
        .into_iter()
        .next()
        .context("No monitors reported by hyprctl")
}

/// Query `hyprctl workspaces -j` and return parsed info.
pub async fn get_active_workspace() -> Result<WorkspaceInfo> {
    if !detect_hyprland() {
        anyhow::bail!("Hyprland not detected");
    }
    let output = tokio::process::Command::new("hyprctl")
        .args(["workspaces", "-j"])
        .output()
        .await
        .context("Failed to execute hyprctl workspaces -j")?;
    if !output.status.success() {
        anyhow::bail!(
            "hyprctl exited with status {:?}",
            output.status.code()
        );
    }
    let workspaces: Vec<WorkspaceInfo> =
        serde_json::from_slice(&output.stdout).context("Failed to parse hyprctl JSON")?;
    workspaces
        .into_iter()
        .next()
        .context("No workspaces reported by hyprctl")
}

/// Generate a floating window rule string for `hyprland.conf`.
/// This is purely documentation/generation; users must paste it manually.
pub fn send_floating_hint(class_name: &str) -> String {
    format!(
        "windowrulev2 = float,class:{}\nwindowrulev2 = size 800 600,class:{}\n",
        class_name, class_name
    )
}

/// Configuration hints for a compact "picker" mode window.
pub fn picker_mode_config(class_name: &str) -> String {
    format!(
        "# Picker mode for {}\n\
         windowrulev2 = float,class:{}\n\
         windowrulev2 = size 900 650,class:{}\n\
         windowrulev2 = center,class:{}\n\
         windowrulev2 = borderless,class:{}\n",
        class_name, class_name, class_name, class_name, class_name
    )
}

/// Attempt to read system accent colors generated by pywal or matugen.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SystemColors {
    pub accent: Option<String>,
    pub background: Option<String>,
    pub foreground: Option<String>,
    pub colors: Vec<String>,
}

/// Read `~/.cache/wal/colors.json` (pywal) if present.
fn read_pywal_colors() -> Option<SystemColors> {
    let cache = dirs::cache_dir()?;
    let path = cache.join("wal").join("colors.json");
    if !path.exists() {
        return None;
    }
    trace!("Reading pywal colors from {:?}", path);
    let contents = std::fs::read_to_string(&path).ok()?;
    let json: serde_json::Value = serde_json::from_str(&contents).ok()?;
    let colors = json.get("colors")?.as_object()?;
    let mut list: Vec<String> = Vec::new();
    let mut keys: Vec<_> = colors.keys().cloned().collect();
    keys.sort();
    for k in keys {
        if let Some(v) = colors.get(&k).and_then(|v| v.as_str()) {
            list.push(v.to_string());
        }
    }
    Some(SystemColors {
        accent: list.first().cloned(),
        background: json.get("special").and_then(|s| s.get("background")).and_then(|v| v.as_str()).map(|s| s.to_string()),
        foreground: json.get("special").and_then(|s| s.get("foreground")).and_then(|v| v.as_str()).map(|s| s.to_string()),
        colors: list,
    })
}

/// Read `~/.config/matugen/config.toml` or cached theme if present.
fn read_matugen_colors() -> Option<SystemColors> {
    // Matugen typically writes to ~/.config/matugen/
    let config = dirs::config_dir()?.join("matugen");
    // Check for a cached scheme file or template output.
    let scheme = config.join("colors.json");
    if !scheme.exists() {
        // fallback: check cache
        let cache = dirs::cache_dir()?.join("matugen").join("colors.json");
        if !cache.exists() {
            return None;
        }
        let contents = std::fs::read_to_string(&cache).ok()?;
        return parse_matugen_json(&contents);
    }
    let contents = std::fs::read_to_string(&scheme).ok()?;
    parse_matugen_json(&contents)
}

fn parse_matugen_json(text: &str) -> Option<SystemColors> {
    let json: serde_json::Value = serde_json::from_str(text).ok()?;
    let colors = json.get("colors")?.as_object()?;
    let mut list = Vec::new();
    for (_k, v) in colors.iter() {
        if let Some(s) = v.as_str() {
            list.push(s.to_string());
        } else if let Some(s) = v.get("hex").and_then(|h| h.as_str()) {
            list.push(s.to_string());
        }
    }
    Some(SystemColors {
        accent: json.get("primary").and_then(|p| p.as_str()).map(|s| s.to_string()),
        background: json.get("background").and_then(|p| p.as_str()).map(|s| s.to_string()),
        foreground: json.get("foreground").and_then(|p| p.as_str()).map(|s| s.to_string()),
        colors: list,
    })
}

/// Attempt to read system colors from known generator paths.
/// Returns `None` if neither pywal nor matugen output is found.
pub fn read_system_colors() -> Option<SystemColors> {
    if let Some(colors) = read_pywal_colors() {
        debug!("Found pywal colors");
        return Some(colors);
    }
    if let Some(colors) = read_matugen_colors() {
        debug!("Found matugen colors");
        return Some(colors);
    }
    warn!("No system color files found (checked pywal and matugen)");
    None
}

/// Minimal wrapper around `which` crate logic without adding a dependency.
mod which {
    use std::path::PathBuf;
    pub fn which(name: &str) -> Result<PathBuf, std::io::Error> {
        let paths = std::env::var_os("PATH").unwrap_or_default();
        for dir in std::env::split_paths(&paths) {
            let candidate = dir.join(name);
            if candidate.is_file() {
                return Ok(candidate);
            }
        }
        Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("{} not found in PATH", name),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_hyprland_without_env() {
        // Ensure it doesn't panic when env is not set and hyprctl absent.
        let original = std::env::var_os("HYPRLAND_INSTANCE_SIGNATURE");
        std::env::remove_var("HYPRLAND_INSTANCE_SIGNATURE");
        // We can't easily remove hyprctl from PATH in all test environments,
        // but detect_hyprland gracefully handles absence.
        let _ = detect_hyprland();
        if let Some(val) = original {
            std::env::set_var("HYPRLAND_INSTANCE_SIGNATURE", val);
        }
    }

    #[test]
    fn test_detect_hyprland_with_env() {
        std::env::set_var("HYPRLAND_INSTANCE_SIGNATURE", "test-instance");
        assert!(detect_hyprland());
        std::env::remove_var("HYPRLAND_INSTANCE_SIGNATURE");
    }

    #[test]
    fn test_send_floating_hint_contains_class() {
        let rule = send_floating_hint("hyprfiles");
        assert!(rule.contains("hyprfiles"));
        assert!(rule.contains("float"));
    }

    #[test]
    fn test_picker_mode_config() {
        let cfg = picker_mode_config("hyprfiles");
        assert!(cfg.contains("float"));
        assert!(cfg.contains("center"));
    }

    #[test]
    fn test_parse_pywal_colors() {
        let json = r##"{
            "colors": {
                "color0": "#1d2021",
                "color1": "#cc241d"
            },
            "special": {
                "background": "#1d2021",
                "foreground": "#ebdbb2"
            }
        }"##;
        let colors = read_pywal_colors(); // depends on file existing
        // Instead test internal parse by writing temp file
        let dir = tempfile::tempdir().unwrap();
        let wal_dir = dir.path().join("wal");
        std::fs::create_dir_all(&wal_dir).unwrap();
        std::fs::write(wal_dir.join("colors.json"), json).unwrap();
        // Mock cache dir via env trick: not possible for dirs::cache_dir,
        // so we test parse_matugen_json and indirectly the pywal path.
        // We'll just assert that parse_matugen_json works with similar shape.
        let parsed = parse_matugen_json(json).unwrap();
        assert!(parsed.colors.len() >= 2);
    }

    #[test]
    fn test_read_system_colors_graceful_missing() {
        // Should not panic when files are missing.
        let _ = read_system_colors();
    }
}
